apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: travel
spec:
  clusterIP: None
  ports:
    - port: 3307
      protocol: TCP
      targetPort: 3307
  selector:
    app: mysql
