apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: init-volume
          configMap:
            name: init-db
      containers:
        - name: mysql
          image: mariadb:latest
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-config
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
              readOnly: true

