apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mytravel-ingress
  namespace: travel
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - host: mytravel123.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 4200
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: backend-auth-service
                port:
                  number: 5000
          - path: /api/tours/
            pathType: Prefix
            backend:
              service:
                name: backend-tours-service
                port:
                  number: 5001
